### ISSUE TITLE
Failed to initialize libusb

### ISSUE THREAD

**Issue by rjkz808** [loomnetwork/loom-js#314] opened 2019-10-01 19:19 UTC
## Description

When I run node.js script which uses `loom-js` it logs this message to the console:

```bash
Failed to initialize libusb.
```

This behavior of `loom-js` is unexpected because we don't use any USB-related packages.

## Verions

- Node.js: v10.16.3
- loom-js: v1.59.1

**Comment by rjkz808** [comment] 2019-10-02 09:54
I also shot a video that shows the problem:

![issue](https://media.giphy.com/media/Xymd39N6dAcqWQsc7k/giphy.gif)

**Comment by eduardonunesp** [comment] 2019-10-02 15:32
Hi @rjkz808, I was investigating that issue and looks like you're testing on a `WSL`, well I tested here inside a `WSL` distro also and it failed too, likely the issue is because that distro don't have a `/dev/usb` device available to be used by `lib/usb`, we're using `usb` inside `loom-js` in order to support `Ledger Wallet`, so if you're doing something that utilizes the `usb` with `loom-js` I recommend you to use a distro or SO that supports usb drivers/modules, otherwise you can ignore that `warning`

**Comment by enlight** [comment] 2021-06-03 15:38
Closing this since it's not something we can fix in loom-js itself.

**Closed by enlight** 2021-06-03 15:38 UTC
Labels: Investigate
